on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Build on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
    - name: Install dependencies (ubuntu-latest)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install libncursesw5-dev libprotobuf-dev
    - name: Install dependencies (macos-latest)
      if: matrix.os == 'macos-latest'
      run: |
        brew install protobuf
    - name: Initialize Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Initialize Java
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Execute build
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: build --no-daemon
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ github.token }}
